### ISSUE TITLE
Accumulative Energy Usage Unavailable, Errors In Logs

### ISSUE THREAD

**Issue by stuartmacd** [dan-r/HomeAssistant-Ohme#52] opened 2024-02-04 10:38 UTC
**What happened?**
The Accumulative Energy Usage sensor is marked as unavailable in HA and has no data:

![IMG_1798](https://github.com/dan-r/HomeAssistant-Ohme/assets/29892836/15d57b10-89b5-4cac-9680-94cd1388c959)

The usage data is available in the Ohme app:

![IMG_1800](https://github.com/dan-r/HomeAssistant-Ohme/assets/29892836/a37429f5-6c3d-4490-9e1c-e6cd0069ab68)

**Expected behavior**
The energy usage to match the data available in the Ohme app.

**Log Output**
Please note I have replaced what looks like a user token with a “USERID” string below:

```
Logger: custom_components.ohme.api_client
Source: custom_components/ohme/api_client.py:108
Integration: Ohme (documentation, issues)
First occurred: February 3, 2024 at 10:34:58 PM (25 occurrences)
Last logged: 10:05:24 AM

Ohme API response error: /v1/chargeSessions/summary/users/USERID?&startTs=1546300800000&endTs=1709251199000&granularity=MONTH, 500; {"timestamp":1707033920882,"status":500,"error":"Internal Server Error","message":"Mapped Measurements were empty! Likely because wh was null. ","path":"/v1/chargeSessions/summary/users/USERID"}
```

**Home Assistant Version**
2024.1.5

**Integration Version**
0.5.1

**Additional context**
Other sensors work fine. Charger is an Ohme Home Pro. Happy to help fix/debug.

**Comment by dan-r** [comment] 2024-02-04 14:10
Closed as duplicate of #33

**Closed by dan-r** 2024-02-04 14:10 UTC
Labels: bug
