### ISSUE TITLE
Up to 5 minute lag on binary_sensor.ohme_car_charging

### ISSUE THREAD

**Issue by andyvee69** [dan-r/HomeAssistant-Ohme#13] opened 2023-12-29 09:45 UTC
**Describe the bug**
The binary sensor has in some instances a lag of over 5 minutes from when the car stops charging to when it changes state to off

**To Reproduce**
Observe during an active charge session where Ohme are using multiple 15 minute charge slots. Car stops charging on the 15 minute boundary, binary sensor can take over 5 minutes before it changes state to reflect this

**Expected behavior**
Binary sensor to update within a minute

**Screenshots**
![Screenshot_2023-12-29-09-43-06-302_io homeassistant companion android](https://github.com/dan-r/HomeAssistant-Ohme/assets/35867564/a4bb9e14-6f15-4507-a8e4-4002e98b221a)

**Home Assistant Version**
Core 2023.12.4
Supervisor 2023.12.0
OS 11.2
Frontend 20231308.2

**Integration Version**
0.1.8

**Additional context**

**Comment by dan-r** [comment] 2023-12-29 10:00
I can reproduce this. Attached screenshot shows power draw sensor vs CT clamp for garage. Once the actual draw drops to 0w, the Ohme reported wattage drops to ~800w for a few minutes before going to 0w. Looks like it could be more of a moving average than an instantaneous measurement. 

The car charging sensor currently just checks if power draw > 0 as the API doesn't expose any indication the car is charging besides this. 

I'm inclined to say it's an API limitation, but another approach would be to either:
1. Update the car charging sensor to interpret whether we are in a 'smart charge slot' rather than evaluating power draw
2. Add a separate sensor for option 1 and keep the car charging sensor as is

What are your thoughts around this, and what would work best for your current use case?

![image](https://github.com/dan-r/HomeAssistant-Ohme/assets/1384852/e3b48242-2473-4a43-b7b9-ab52d382f0bb)

**Comment by andyvee69** [comment] 2023-12-29 11:07
If the current draw drops to less than 1.4kW it isn't charging anyway. So on a change of state from >1400 to <1400 change the binary sensor to off.

For sensing off to on though, it would still need to be a change from 0 to >0.


I'm not sure what you mean by 'interpret if in a smart charge slot' though. You could still have a situation where if too much charge had been scheduled therefore in a planned charge slot, but the Ohme still delivering zero current as the car is no longer accepting charge.

Current draw is the only reliable measure.

**Comment by dan-r** [comment] 2023-12-29 11:22
That doesn't hold true for my car - if I charge to 100%, it tapers off and sits at ~950w for a good hour or so. I worry that with PHEVs which only charge at 3kW anyway, having an arbitrary 'cut-off' could introduce strange results.

By 'interpret if in a smart charge slot' I was suggesting an additional sensor to say that the Ohme is offering power, whether or not the car is drawing anything.

**Comment by andyvee69** [comment] 2023-12-29 11:28
Maybe you are looking at the wrong API field then. Charger current would be a better indicator than an averaged power figure.

The actual current and voltage readings update every 10 secs I am led to believe :)

**Comment by brutus6** [comment] 2023-12-30 08:24
Not sure if it helps, but results from last night. I did a charge last night and got the same issue on v0.2.1. See screenshot.

![Image](https://github.com/dan-r/HomeAssistant-Ohme/assets/131045297/18705296-083b-479d-8cd7-f6c994cc6ab0)

The Octopus Mini and my IHD both showed the power drop to normal house usage bang on 8am and the CT clamp I have on the live on my EV supply showed it drop to 0kwh at 8am, but Ohme API via the new integration shows approx 4kWh for 5 mins after the charge ended and so Car Charging sensor was on for 5 mins after the charging stopped until Ohme was reporting 0kWh.

**Comment by dan-r** [comment] 2023-12-30 10:59
@brutus6 can you check the current draw (amps) sensor and see if that had the same lag please?

**Comment by brutus6** [comment] 2023-12-30 11:10
Yes. Same lag of 5 mins. The amps went from 32 to 17 for 5 mins before hitting 0.

![Image](https://github.com/dan-r/HomeAssistant-Ohme/assets/131045297/70477910-fb95-4b62-8e6a-62cff39d9298)

**Comment by dan-r** [comment] 2023-12-30 11:39
How annoying. So I've got a couple of ideas to combat this, but the winning one for now is:

If current draw has dropped more than 40% since the least reading 
AND
CT clamp reading is less than the current draw
=
Assume not charging until the current draw next hits 0

**Comment by andyvee69** [comment] 2023-12-30 12:06
It seems if you increase the API polling rate to every 10 secs for the CT clamp and the session info this is negated somewhat. I need to do further testing. I'm not sure if it is because you are doing multiple API requests at different intervals?
![Screenshot 2023-12-30 12 05 43](https://github.com/dan-r/HomeAssistant-Ohme/assets/35867564/05250375-b2eb-4e98-990a-8be4a79f1005)

**Comment by dan-r** [comment] 2023-12-30 12:51
Currently:
* CT reading comes every minute 
* Current/power readings come every 30s
It looks like the CT reading reflects the charge stopping straight away. 

Ideally I don't want to make these any more frequent as to not get on the wrong side of Ohme, but of course you are free to change the code or trigger the update routines through an automation. 

A sub-60s delay on the charging state sensor seems acceptable to me, so I'll try and get something in today with CT based charge state detection.

My Ohme is installed on the garage, with the CT on the garage supply so will ordinarily be 0 when the car isn't charging. @andyvee69 @brutus6 if one/both of you have the CT on the whole home supply it'd be useful extra data after this goes in, with bonus points for additional night time loads :)

**Comment by andyvee69** [comment] 2023-12-30 13:37
I don't think using the CT clamp reading is the correct approach for a number of reasons - older units do not have CT clamps, not everyone has the CT clamp fitted with Pro/ePod, if you have home solar or battery storage then the CT clamp measuring total grid import may not necessarily reflect what is happening with charging current.

**Comment by dan-r** [comment] 2023-12-30 13:48
It would be trivial to detect whether the clamp is present (eg. have we ever seen it go over 0), and I think it could be quite useful as an additional metric for the binary sensor if available. 

I hadn't thought about the solar/battery storage aspect though. That complicates things, especially with no support for multiple clamps.

Perhaps I'll instead try to interpret that sudden drop as no longer charging?

**Comment by JaseCat** [comment] 2023-12-30 14:01
@andyvee69 what did you do to get the Current draw to update quicker? (looks like it's updating every 5 seconds on you screenshot above)?  
@dan-r This integration is brilliant! I've been wanting to create some Automations in HA to stop the OHME from draining my home battery setup when I get charge slots outside of the 23:30 - 05:30 period.  
I've got it setup but as there is currently a 5 min delay on the updates it means potentially I'd be pulling from the grid until the integration updates and reports either 0amp/watts which then turns my batteries back on.  Hope that makes sense!

**Comment by andyvee69** [comment] 2023-12-30 14:03
It might be a valid sudden power drop from 7kw to 1.4kW charging though.

**Comment by andyvee69** [comment] 2023-12-30 14:04
> @andyvee69 what did you do to get the Current draw to update quicker? (looks like it's updating every 5 seconds on you screenshot above)?

Altered the code. I'll let @dan-r explain :)

**Comment by brutus6** [comment] 2023-12-30 14:11
> How annoying. So I've got a couple of ideas to combat this, but the winning one for now is:
> 
> If current draw has dropped more than 40% since the last reading AND CT clamp reading is less than the current draw THEN Assume not charging until the current draw next hits 0
> 
> @brutus6 did the Ohme CT reading sensor drop quickly?

Unfortunately, as @andyvee69 pointed out, I don't have a CT clamp fitted into my Ohme ePod for load balancing (so it just shows 0amps for me) as I don't have solar, battery or any other high load items in the house and a 100amp cut out, so a CT was not required.

The CT clamp I refer to is a custom built one that uses ESPhome and connects to HA to give me the load on the live wire for my charger.

**Comment by dan-r** [comment] 2023-12-30 14:38
> It might be a valid sudden power drop from 7kw to 1.4kW charging though.

That's true - it seems inconsistent from my testing but seems to be some sort of average for the current and power draw.

> what did you do to get the Current draw to update quicker? (looks like it's updating every 5 seconds on you screenshot above)?

You can update the intervals in your local copy of [coordinator.py](https://github.com/dan-r/HomeAssistant-Ohme/blob/main/custom_components/ohme/coordinator.py), but this is overwritten with every intergration update.

> Unfortunately, as @andyvee69 pointed out, I don't have a CT clamp fitted into my Ohme ePod for load balancing (so it just shows 0amps for me) as I don't have solar, battery or any other high load items in the house and a 100amp cut out, so a CT was not required.

Yeah thats fair enough, and will especially be true for the portable models.


@andyvee69 it seems (but correct me if I'm wrong) as if your main reason for reducing the lag is to coordinate your external loads to only come on when the power is cheap. An alternative to polling more often could be to have a binary sensor to say 'we are in a smart charge slot, power is cheap!', and so just interpret if at the current time we are midway through an upward sloping line on the charge graph?

**Comment by JaseCat** [comment] 2023-12-30 14:41
Thanks @dan-r  I did change it to this; (but it hasn't changed the amount it's logging)

class OhmeChargeSessionsCoordinator(DataUpdateCoordinator):
    """Coordinator to pull main charge state and power/current draw."""

    def __init__(self, hass):
        """Initialise coordinator."""
        super().__init__(
            hass,
            _LOGGER,
            name="Ohme Charge Sessions",
            update_interval=timedelta(seconds=10),
        )

**Comment by dan-r** [comment] 2023-12-30 14:49
@JaseCat Did you restart home assistant afterwards? I find reloading the intergration doesn't always reload everything. Also worth noting that if those values haven't changed, the states won't show as updated in home assistant.

**Comment by andyvee69** [comment] 2023-12-30 14:59
> your main reason for reducing the lag is to coordinate your external loads to only come on when the power is cheap. An alternative to polling more often could be to have a binary sensor to say 'we are in a smart charge slot, power is cheap!', and so just interpret if at the current time we are midway through an upward sloping line on the charge graph?

No, it isn't. It is the exact opposite actually - it iis accurately controlling the turning off of high loads. I know how people are going to use this binary sensor for controlling other loads and in particular charging home battery storage. So if the binary sensor is incorrectly showing that the car is charging at 3 minutes past the hour, or 3 minutes past the half hour, but the charging has now stopped, people are going to incorrectly assume that the next half hour period is now at off peak so force charge batteries etc etc. Interpreting the graph is of little value either as the vehicle has to be activley charging. Knowing that some people set schedules to add 2 or 3 times the amount of charge they actually require, the graph is fairly meaningless as the car could have hit its charge limit or be full. So even though Ohme are trying to charge it, the current would be zero and therfore you are no longer at off-peak (unless during 23:30-05:30 obviously).

The only way of accurately knowing if the car is charging or not is with an accurate current (or power) reading.

**Comment by andyvee69** [comment] 2023-12-30 14:59
> but it hasn't changed the amount it's logging

Are you plugged in and actively charging?

**Comment by JaseCat** [comment] 2023-12-30 15:03
Just did a restart and it's still only reporting every 5 mins.  @andyvee69 Yes, I did a test charge to see if it would update quicker. I've attached a screenshot. 
<img width="848" alt="image" src="https://github.com/dan-r/HomeAssistant-Ohme/assets/133496072/bef339bb-4b80-47b2-9139-c2c665786d99">

**Comment by dan-r** [comment] 2023-12-30 15:07
> Knowing that some people set schedules to add 2 or 3 times the amount of charge they actually require, the graph is fairly meaningless as the car could have hit its charge limit or be full. So even though Ohme are trying to charge it, the current would be zero and therfore you are no longer at off-peak (unless during 23:30-05:30 obviously).

I was under the impression that if Ohme are trying to charge it, that means power is cheap regardless of whether the car is pulling anything. It seems to be that way for me at least, although its hard to test because I have to wait for my next statement to see what I was billed at.



> Just did a restart and it's still only reporting every 5 mins. @andyvee69 Yes, I did a test charge to see if it would update quicker. I've attached a screenshot.

I expect its just the values not changing in the API. It may be possible to trigger an update, but that risks abusing the service and causing a lot of data traffic.

**Comment by JaseCat** [comment] 2023-12-30 15:09
@dan-r I'd be happy with it being 30 seconds as per your original settings. But I don't even get that....

**Comment by andyvee69** [comment] 2023-12-30 15:32
> I was under the impression that if Ohme are trying to charge it, that means power is cheap regardless of whether the car is pulling anything

Err, no. Otherwise I could set in the Ohme app that I have a car with a 120kWh battery, set it to Add 100% charge, plug in and get almost endless off-peak electricity as my 40kWh car that only needs 10kWh to charge to 100% would be full after an hour and a half. Ohme would have scheduled 18hrs of charging, and as my car had stopped accepting charge would keep extending the session.
The car has to be actively charging in a half hour billing period for it to be off-peak (outside of 23:30-05:30) regardless of if Ohme are still trying to force charge in to a an already full car or not.

**Comment by dan-r** [comment] 2023-12-30 16:43
> @dan-r I'd be happy with it being 30 seconds as per your original settings. But I don't even get that....
It seems to be a limitation of the API. The integration is pulling every 30 seconds but the data its getting back just isn't changing.

>  The car has to be actively charging in a half hour billing period for it to be off-peak (outside of 23:30-05:30) regardless of if Ohme are still trying to force charge in to a an already full car or not.
Interesting, I always thought that was a possibility but just against the IOG terms.

**Comment by andyvee69** [comment] 2023-12-30 16:51
> but just against the IOG terms

??? Not sure what you mean. If Octopus/Ohme have scheduled the car to be charging, and it is charging, why is that in breach of Ts&C's?

**Comment by dan-r** [comment] 2023-12-30 16:52
> ??? Not sure what you mean. If Octopus/Ohme have scheduled the car to be charging, and it is charging, why is that in breach of Ts&C's?

I meant the case of stating a larger car battery and percentage effectively 'gaming' IOG to get more cheap energy

**Comment by andyvee69** [comment] 2023-12-30 17:02
> stating a larger car battery and percentage effectively 'gaming' IOG to get more cheap energy

But it doesn't work. Because the car has to be actively charging. Which was my point. So using a planned charge slot as an indicator has limited value, as if the car isn't charging because it is already full, it isn't off peak.

The only reliable indicator is if the Ohme is delivering power or not.

Maybe some logic can be built for the car is charging binary sensor based around charge current has suddenly dropped and no longer in a planned charge slot. This would have to be evaluated within a minute after the hour and half hour to line up with billing periods. The 15 minute boundary doesn't really matter as the off peak continues to the end of the 30 minute billing period anyway.

**Comment by dan-r** [comment] 2023-12-30 17:09
The latest version has a 'charge slot active' sensor. Although not particularly useful on its own, the idea is to keep an eye on it then see if its possible to add some logic like you say.

Current best approach is:
IF
Sudden current drop of 40%+ since last reading
AND
Not in a charge slot
AND
Charge slot ended within the past minute
THEN
Override car charging binary sensor for 5 minutes before resuming normal criteria of power > 0

**Comment by JaseCat** [comment] 2023-12-30 17:10
Sounds good @dan-r

**Comment by dan-r** [comment] 2023-12-30 17:12
That should get the delay down to a maximum of 30 seconds. I'm sure it would be possible to do targeted refreshes on the time boundary to get it down further, but under 30s seems good enough to me.

**Comment by andyvee69** [comment] 2023-12-30 17:14
Sounds good, but only needs to be checked twice an hour at maybe xx:00:45 and xx:30:45 as a few minutes delay at any other time makes no difference .

**Comment by dan-r** [comment] 2023-12-30 17:22
The charge graph and charge state (along with a load more) come from `OhmeChargeSessionsCoordinator` when we poll it every 30s, so charge state and charge slot active binary sensors get re-evaluated every 30s too. Not massively efficient but seems to be the way every other integration works and means we get them updated 'for free' without making any extra requests. 

Worst case, with the new logic, if the 30s timer pings at xx:59:59, we'll have accurate 'not charging' state at xx:00:29 (+ network latency).

**Comment by dan-r** [comment] 2023-12-31 00:36
@andyvee69 @JaseCat @brutus6 I've just published an update that seems to get the charge state much quicker in my testing.

Mind testing it out overnight (If you're still awake)?

Now:
![image](https://github.com/dan-r/HomeAssistant-Ohme/assets/1384852/61274318-7406-4af7-a562-8132862d7717)

**Comment by dan-r** [comment] 2023-12-31 11:37
I charged to 100 last night so some very short slots and decreasing loads, but it seems to be working quite well from these couple of examples. Garage power is a Shelly EM. 

![image](https://github.com/dan-r/HomeAssistant-Ohme/assets/1384852/e542a891-b22e-4f39-8a4a-3832108f5612)

![image](https://github.com/dan-r/HomeAssistant-Ohme/assets/1384852/fe4535cc-3fd0-4e80-bfa7-1bc59f169b0e)

**Comment by brutus6** [comment] 2023-12-31 12:43
Downloaded the latest version and the lag is now only about 20 seconds in reality. However, and really not sure how important it is for people with batteries, but there is still a lag of 5 mins at about just 97W. Lol.

![Screenshot_20231231-123721](https://github.com/dan-r/HomeAssistant-Ohme/assets/131045297/8d7563b1-e312-4aa6-ae47-ca79ec600c6d)

Much better. Well done @dan-r, good work.

**Comment by dan-r** [comment] 2023-12-31 12:46
@brutus6 is that v0.2.3? When you say the lag is ~20 seconds is that on the charging binary sensor?

**Comment by JaseCat** [comment] 2023-12-31 13:27
Updated to 0.2.3 and mine is still only reporting every 5 mins…
![IMG_4110](https://github.com/dan-r/HomeAssistant-Ohme/assets/133496072/b83f2a65-529d-4c32-9ecb-d76ba199a942)

**Comment by dan-r** [comment] 2023-12-31 13:36
> Updated to 0.2.3 and mine is still only reporting every 5 mins…

There's no way to get readings more often or more accurate, however often you poll. The API just returns (what appears to be) a moving average of the past 5 minutes. 

0.2.3 adds some logic to the charging binary sensor to detect the sudden drop and report as not charging. The power/current sensors are unchanged.

**Comment by hoggyhoggy** [comment] 2023-12-31 13:51
Sorry, bit late to the party on this one. Having had several years poking around this, you may find some further joy by taking into account the battery SOC data fields (x[0].batterySoc.wh specifically) which do tend to keep moving (or not) depending on if it's charging or not. You get roughly 1Wh increments per sec even when trickle charging a 6A. 

 "batterySoc": {
            "wh": 128,
            "rangeKm": 0.0,
            "percent": 0.0,
            "timestamp": 1704029913593,
            "highPrecision": null,
            "maxRangeKm": null 

Notes: Don't confuse this batterySOC fields with the identically names one under the "Car"fields. That one only increments if car is API compatible AFAIK.   
Beware also, vehicles have quirks. For instance, MG ZS Trickle charge will produce a constant 6A charge, however it will not intiate the power/voltage/current fields which will remain NULL. 

I'll post a few other helpful tips on another thread. 
Terravolt.

**Comment by brutus6** [comment] 2023-12-31 14:28
> @brutus6 is that v0.2.3? When you say the lag is ~20 seconds is that on the charging binary sensor?

So for any confusion. So I am comparing the Ohme Power Draw and Ohme Current Draw in your integration vs, my own custom CT clamp that I have fitted to the live wire on the charger, which until know I have been using to tell me if the charger is charging the car or not.

So for me it is more than sorted. Thanks.

I was just pointing out the smallest of differences (in terms of the lag 20 seconds between the Ohme and my custom CT clamp and the 5 min lag at 97w - I mean I don't know if they are issues for those with batteries or not. @andyvee69 will be better to confirm on that I am sure.

As I said, as far as I am concerned, it is more than close enough to my custom CT clamp reading that I have been using.

**Comment by dan-r** [comment] 2023-12-31 18:01
> Sorry, bit late to the party on this one. Having had several years poking around this, you may find some further joy by taking into account the battery SOC data fields (x[0].batterySoc.wh specifically) which do tend to keep moving (or not) depending on if it's charging or not. You get roughly 1Wh increments per sec even when trickle charging a 6A. 
> 
> 
> 
>  "batterySoc": {
> 
>             "wh": 128,
> 
>             "rangeKm": 0.0,
> 
>             "percent": 0.0,
> 
>             "timestamp": 1704029913593,
> 
>             "highPrecision": null,
> 
>             "maxRangeKm": null 
> 
> 
> 
> Notes: Don't confuse this batterySOC field with the identically named sub one under the "Car". That one only increments if car is API compatible AFAIK.   
> 
> Beware also, vehicles have quirks. For instance, MG ZS Trickle charge will produce a constant 6A charge, however it will not initiate the power/voltage/current fields AT ALL which will remain NULL. MG ZS normal will work as expected. 
> 
> 
> 
> I'll post a few other helpful tips on another thread. 
> 
> Terravolt.  

That's very interesting, I hadn't been looking at that at all, assuming it was only for API compatible cars. 

Happy new year, and I look forward to hearing more tips from you :)

**Comment by dan-r** [comment] 2024-01-01 20:51
@andyvee69 I've re-written some of the charge state detection logic in v0.2.5 so it now uses a combination of:
* Mainly the batterySoc.wh field - but on the boundary we ALWAYS see some 1+ delta, meaning it takes 2 ticks (1 minute) to get the state change
* Charge slot data - a sudden drop on a boundary is interpreted as charge having stopped, which avoids the extra tick delay above
* Power draw - if all else fails or we don't have the data we need, revert to power draw over 0 watts.

So in my testing I get the charge state updated in less than 30 seconds. I'll give it a proper test tonight and report back, but some extra eyes on it wouldn't hurt.

The logic is [here](https://github.com/dan-r/HomeAssistant-Ohme/blob/0c04e55df8d70251c1d2788704bea7d5e48726d7/custom_components/ohme/binary_sensor.py#L126) and is extensively commented.

Thanks to @hoggyhoggy for pointing that field out! 

![image](https://github.com/dan-r/HomeAssistant-Ohme/assets/1384852/7033fc9a-ebe6-4a73-9ede-fade09a45258)

**Comment by hoggyhoggy** [comment] 2024-01-02 09:58
Looks good, Just so it's clear: 
_ # Failing that, we use the watt hours field to check charge state:
        # - If Wh has positive delta and a nonzero power reading, we are charging
        # This isn't ideal - eg. quirk of MG ZS in #13, so need to revisit_

It's not the Wh value that stays Null in this case, it's the Power values that stay Null (the Wh still increments).
This is only when using the MG ZS in Trickle mode (which I imagine is pretty rare) although there might be others. Normal MG ZS selected works as expected - power, voltage, amps...

**Comment by dan-r** [comment] 2024-01-02 10:59
@hoggyhoggy its badly written but what I meant was that one of the conditions for charging in progress is power draw (w) > 0, which we ideally don't want to avoid issues like you mentioned with the power values staying null. 

The latest version works well to detect charge state in my testing, BUT gives some funky results if I charge my car to 100%. The power draw pattern is strange to say at the least. The drops to 0 at 4:46 and onwards should register as 'not charging' but the downward slope should still show as charging. More testing to do here! 

<img width="1451" alt="Screenshot 2024-01-02 at 10 57 05" src="https://github.com/dan-r/HomeAssistant-Ohme/assets/1384852/33566e1e-263b-4fcc-8d58-d56fa86f8d94">

**Comment by andyvee69** [comment] 2024-01-02 12:19
I'm seeing some unexpected behaviour with the binary sensor for car is charging

![Screenshot_2024-01-02-12-17-21-965_io homeassistant companion android](https://github.com/dan-r/HomeAssistant-Ohme/assets/35867564/a1947fde-2fa9-49bb-bb47-7f7b49aad57d)

**Comment by dan-r** [comment] 2024-01-02 12:27
@andyvee69 are any those 'dropouts' longer than 1 update cycle? (~30s).

If not, I'll put out an update this evening to fix that.

**Comment by andyvee69** [comment] 2024-01-02 12:32
Seem to be exactly 30 seconds
![Screenshot_2024-01-02-12-31-03-448_io homeassistant companion android](https://github.com/dan-r/HomeAssistant-Ohme/assets/35867564/8ff2db2d-2a30-48db-8cd3-68595b52d261)

**Comment by dan-r** [comment] 2024-01-02 12:58
Thought so - I've got a fix for that ready, so check back this evening. 

It should get the delay down to under 30 seconds on the boundary of a charge slot and under 60 seconds if for example the car hits its limit and stops pulling. 

Thanks for your patience!

**Comment by dan-r** [comment] 2024-01-03 12:31
@andyvee69 have you had a chance to test the latest changes? Seems to be reliable in my testing now.

**Comment by andyvee69** [comment] 2024-01-03 12:34
I'll give it a test tonight

**Comment by andyvee69** [comment] 2024-01-04 06:59
Seems to be working well
![Screenshot_2024-01-04-06-57-52-906_io homeassistant companion android](https://github.com/dan-r/HomeAssistant-Ohme/assets/35867564/4db2d515-5c1a-4ac9-8b11-19e1071fb0c3)

**Comment by dan-r** [comment] 2024-01-04 08:46
Good news, thanks for testing!
I'll close this for now.

**Closed** 2024-01-04 08:47 UTC
Labels: bug, api-limitation
